[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

[project]
name = "litestar-template"
version = "0.1.0"
description = "Litestar template"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Aliaksei Yafremau", email = "aleksey.yafremau@gmail.com" }
]

dependencies = [
    "litestar>=2.15.1",
    "uvicorn>=0.34.0",
]

[project.optional-dependencies]
lint = [
    "flake8>=7.1.2",
    "ruff>=0.11.2",
    "wemake-python-styleguide>=1.1.0",
]
